In [135]:
import matplotlib.pyplot as ply
% matplotlib inline

In [28]:
import torch
import torch.nn as nn

x = torch.tensor([2.0])

class Linear_Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.lm1 = nn.Linear(1,1,bias=False)
        self.lm2 = nn.Linear(1,1,bias=True)
    def forward(self, X):
        out = self.lm1(X) + self.lm2(X)
        
        return out

mdl = Linear_Model()

In [31]:
print(list(mdl.parameters()))

[Parameter containing:
tensor([[-0.2707]]), Parameter containing:
tensor([[-0.7197]]), Parameter containing:
tensor([ 0.2062])]


In [32]:
print(mdl(x))

tensor([-1.7746])


In [125]:
import torch
import torch.nn as nn

x = torch.arange(10).view(-1,1)
y = -3 * x

class NN_Linear_Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.lm = nn.Linear(1,1)
    def forward(self, X):
        out = self.lm(X)
        
        return out

mdl = NN_Linear_Model()

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(mdl.parameters(), lr=0.0001)

for i in range(100):
    optimizer.zero_grad()
    y_pred = mdl(x)
    loss = loss_fn(y_pred, y)
    loss.backward()
    optimizer.step()
    for p in mdl.parameters():
        p.data.clamp_(0)
    
    if i % 10 == 0:
        print(f'loss is {loss} at iter {i}, weight: {list(mdl.parameters())[0].item()}')

list(mdl.parameters())

loss is 414.9129943847656 at iter 0, weight: 0.8962091207504272
loss is 390.3402404785156 at iter 10, weight: 0.6797359585762024
loss is 348.17059326171875 at iter 20, weight: 0.4752900302410126
loss is 310.55670166015625 at iter 30, weight: 0.2822031080722809
loss is 277.0063171386719 at iter 40, weight: 0.09984404593706131
loss is 256.5 at iter 50, weight: 0.0
loss is 256.5 at iter 60, weight: 0.0
loss is 256.5 at iter 70, weight: 0.0
loss is 256.5 at iter 80, weight: 0.0
loss is 256.5 at iter 90, weight: 0.0


[Parameter containing:
 tensor([[ 0.]]), Parameter containing:
 tensor([ 0.])]

In [109]:
1.00000e-02

0.01

In [110]:
0.01 * -7.1552

-0.071552

In [102]:
torch.optim.SGD?

Init signature: torch.optim.SGD(params, lr=<object object at 0x0000000001C9AD60>, momentum=0, dampening=0, weight_decay=0, nesterov=False)
Docstring:     
Implements stochastic gradient descent (optionally with momentum).

Nesterov momentum is based on the formula from
`On the importance of initialization and momentum in deep learning`__.

Args:
    params (iterable): iterable of parameters to optimize or dicts defining
        parameter groups
    lr (float): learning rate
    momentum (float, optional): momentum factor (default: 0)
    weight_decay (float, optional): weight decay (L2 penalty) (default: 0)
    dampening (float, optional): dampening for momentum (default: 0)
    nesterov (bool, optional): enables Nesterov momentum (default: False)

Example:
    >>> optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
    >>> optimizer.zero_grad()
    >>> loss_fn(model(input), target).backward()
    >>> optimizer.step()

__ http://www.cs.toronto.edu/%7Ehinton/absps/mome

In [ ]:
class DecoderRNN(nn.Module):
    def init(self, embed_size, hidden_size, vocab_size, num_layers=1):
        super(DecoderRNN, self).init()
        self.embed_size = embed_size
        self.hidden_size = hidden_size
        self.vocab_size = vocab_size
        self.num_layers = num_layers
        self.linear = nn.Linear(hidden_size, vocab_size)
        self.embed = nn.Embedding(vocab_size, embed_size)
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers, batch_first = True)

    def forward(self, features, captions):
        embeddings = self.embed(captions)
        embeddings = torch.cat((features.unsqueeze(1), embeddings),1)
        hiddens,_ = self.lstm(embeddings)
        outputs = self.linear(hiddens)
        return outputs

In [ ]:
nn.LSTM(embed_size, hidden_size, num_layers, batch_first = True)

In [ ]:
input_size = embed_size
hidden_size = 
num_layers = 1

In [ ]:
.forward(batch_size, caption_length+1, embed_size)

In [ ]:
seq_len = caption_length+1

In [ ]:
output: (seq_len, batch, num_directions * hidden_size)

In [126]:
nn.LSTM?

Init signature: nn.LSTM(*args, **kwargs)
Docstring:     
Applies a multi-layer long short-term memory (LSTM) RNN to an input
sequence.


For each element in the input sequence, each layer computes the following
function:

.. math::

        \begin{array}{ll}
        i_t = \sigma(W_{ii} x_t + b_{ii} + W_{hi} h_{(t-1)} + b_{hi}) \\
        f_t = \sigma(W_{if} x_t + b_{if} + W_{hf} h_{(t-1)} + b_{hf}) \\
        g_t = \tanh(W_{ig} x_t + b_{ig} + W_{hg} h_{(t-1)} + b_{hg}) \\
        o_t = \sigma(W_{io} x_t + b_{io} + W_{ho} h_{(t-1)} + b_{ho}) \\
        c_t = f_t c_{(t-1)} + i_t g_t \\
        h_t = o_t \tanh(c_t)
        \end{array}

where :math:`h_t` is the hidden state at time `t`, :math:`c_t` is the cell
state at time `t`, :math:`x_t` is the input at time `t`, :math:`h_{(t-1)}`
is the hidden state of the previous layer at time `t-1` or the initial hidden
state at time `0`, and :math:`i_t`, :math:`f_t`, :math:`g_t`,
:math:`o_t` are the input, forget, cell, and output gates, respective

In [128]:
torch.tensor([1.1]).float().long()

tensor([ 1])

In [ ]:
3

In [ ]:
class MINIModel(nn.Module):
    def __init__(self,h0=None):
        super(MINIModel, self).__init__()
        self.h = nn.Linear(3,4)
        if not h0 is None:
            self.h.weight.data = h0
    def forward(self,x):
        return self.h(x)