In [1]:
import numpy as np

In [2]:
a = np.array([[1,3], [2,4], [3,5]])

In [3]:
b = np.array([[1,2],[3,1],[4,2],[5,3]])

In [4]:
np.sqrt(np.square(a-b[:,None,:]).sum(2))

array([[1.        , 2.23606798, 3.60555128],
       [2.82842712, 3.16227766, 4.        ],
       [3.16227766, 2.82842712, 3.16227766],
       [4.        , 3.16227766, 2.82842712]])

In [5]:
a

array([[1, 3],
       [2, 4],
       [3, 5]])

In [6]:
a_sq_sum = np.einsum('ik,ik->i',a,a)

b_sq_sum = np.einsum('ik,ik->i',b,b)

a_dot_b = a.dot(b.T)

np.sqrt(a_sq_sum[:,None]-2*a_dot_b+b_sq_sum[None,:])

array([[1.        , 2.82842712, 3.16227766, 4.        ],
       [2.23606798, 3.16227766, 2.82842712, 3.16227766],
       [3.60555128, 4.        , 3.16227766, 2.82842712]])

In [7]:
b_sq_sum.shape

(4,)

In [8]:
a

array([[1, 3],
       [2, 4],
       [3, 5]])

In [9]:
b

array([[1, 2],
       [3, 1],
       [4, 2],
       [5, 3]])

In [20]:
np.einsum('ik,jk->ijk', a,b)

array([[[ 1,  6],
        [ 3,  3],
        [ 4,  6],
        [ 5,  9]],

       [[ 2,  8],
        [ 6,  4],
        [ 8,  8],
        [10, 12]],

       [[ 3, 10],
        [ 9,  5],
        [12, 10],
        [15, 15]]])

In [21]:
import pandas as pd

In [23]:
df = pd.read_clipboard()

In [26]:
df = df.T.reset_index()

In [28]:
df.columns=['name']

In [30]:
df.name.str.split(',')

0             [Emma, F, 20799]
1           [Olivia, F, 19674]
2           [Sophia, F, 18490]
3         [Isabella, F, 16950]
4              [Ava, F, 15586]
5              [Mia, F, 13442]
6            [Emily, F, 12562]
7          [Abigail, F, 11985]
8          [Madison, F, 10247]
9        [Charlotte, F, 10048]
10           [Harper, F, 9564]
11            [Sofia, F, 9542]
12            [Avery, F, 9517]
13        [Elizabeth, F, 9492]
14           [Amelia, F, 8727]
15           [Evelyn, F, 8692]
16             [Ella, F, 8489]
17            [Chloe, F, 8469]
18         [Victoria, F, 7955]
19           [Aubrey, F, 7589]
20            [Grace, F, 7554]
21             [Zoey, F, 7358]
22          [Natalie, F, 7061]
23          [Addison, F, 6950]
24          [Lillian, F, 6869]
25         [Brooklyn, F, 6767]
26             [Lily, F, 6727]
27           [Hannah, F, 6512]
28            [Layla, F, 6428]
29         [Scarlett, F, 5965]
                 ...          
33014          [Zedrick, M, 5]
33015   