In [1]:
from __future__ import print_function
import torch

In [2]:
from torch.autograd import Variable

In [3]:
x = Variable(torch.ones(2,2), requires_grad=True)

In [4]:
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [5]:
y = x + 2

In [6]:
y.grad_fn

In [7]:
z = y * y * 3

In [8]:
z.grad_fn

In [9]:
out = z.mean()

In [10]:
out

tensor(27.)

In [11]:
out.backward()

In [12]:
x.grad

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])

In [13]:
y.grad_fn?

In [14]:
z.grad

In [15]:
27/4

6.75

In [16]:
z

tensor([[ 27.,  27.],
        [ 27.,  27.]])

In [26]:
import numpy as np

In [27]:
np.e(3)

TypeError: 'float' object is not callable

In [28]:
np.exp(3)

20.085536923187668

In [29]:
np.exp(-3)

0.049787068367863944